on:
  workflow_call:
    inputs:
      input1:
        required: false
        type: string
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Example Step
        run: echo "This is an example job in a reusable workflow."