on:
  workflow_call:
    inputs:
      input1:
        required: false
        type: string

jobs:
  call-workflow-passing-data:
    uses: Chamonex/workflows/.github/workflows/cd-documentation.yaml@main